### ISSUE TITLE
bro you need a supercomputer to run your site

### ISSUE THREAD

**Issue by cat2d2** [kavicastelo/kavicastelo#64]
its laggy and nothing is fitting in the div

**Comment by kavicastelo** [comment]
> its laggy and nothing is fitting in the div

@cat2d2 Yeah, it's possible to bit lag on this site because of the webgl 3d renderings. But not much like you mentioned:? I would appreciate it if you could provide some screenshots of the pages you have struggled ^-^

**Comment by cat2d2** [comment]
possible 🤨 
it's there
just open in a virtual enviornment if you want some lag

**Comment by kavicastelo** [comment]
huh. I knew it ;) This site made for real users. Not for the hackers or cyber maniacs. you wanna some experience on this site, come outside from your virtual environment

**Comment by cat2d2** [comment]
im not in one...

**Comment by cat2d2** [comment]
if you want to experience lag go there
